databases:
  - name: capstone
    databaseName: capstone
    user: capstone

services:
  - type: web
    name: capstone
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn capstone.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: capstone
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
