databases:
  - name: capstone
    databaseName: capstone
    user: capstone
    plan: free # Explicitly request the free tier

services:
  - type: web
    name: capstone
    env: python
    plan: free # Explicitly request the free tier
    buildCommand: "./build.sh"
    startCommand: "chmod +x start.sh && ./start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: capstone
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.12.0
